---
plugins:
  # https://github.com/jest-community/eslint-plugin-jest
  - jest

env:
  node: true
  es2020: true

extends:
  - "airbnb-base"
  - "plugin:jest/recommended"

parserOptions:
  ecmaVersion: 11
  sourceType: module

rules:
  one-var: 0
  no-console: 0
  import/extensions: 0
  one-var-declaration-per-line: 0
