---
plugins:
  # https://github.com/jest-community/eslint-plugin-jest
  - jest

env:
  node: true
  es2022: true

extends:
  - "airbnb-base"
  - "plugin:jest/recommended"

parserOptions:
  ecmaVersion: 13
  sourceType: module

rules:
  one-var: 0
  import/extensions: 0
